### ISSUE TITLE
Add new company: Upstart

### ISSUE THREAD

**Issue by darrellsilver** [fikrikarim/companies-with-successful-pivot#14]
**Company Name?**

Upstart

**What's the company main business today?**

Direct to consumer lending

**What did the company do in the early days?**

Allow people to sell their future earnings for cash today, usually to repay student debt.

**What caused the company to pivot?**

Everyone believes they'll make a million dollars a year someday.

**Source?**

https://en.wikipedia.org/wiki/Upstart_(company)

**Comment by fikrikarim** [comment]
Hey thanks for adding the summary! I changed the description a bit and make this link as the source: https://review.firstround.com/fresh-off-ipo-upstarts-ceo-shares-why-the-startup-isnt-a-typical-success-story

Let me know if you think there could be a better wording or source. Thanks!
