### ISSUE TITLE
Add new company: [company name]

### ISSUE THREAD

**Issue by tlimoncelli** [fikrikarim/companies-with-successful-pivot#15]
**Company Name?**

Mentor Graphics

**What's the company main business today?**

Electronic design automation and CAD Software

**What did the company do in the early days?**

Sold turn-key CAD workstations (i.e. pre-installed EDA and CAD software, pre-configured network, on Apollo (Unix-like) workstations.

**What caused the company to pivot?**

Selling workstations with pre-installed software made sense in the 1980s because often the customers had no other computers (except for finance's mainframe) and certainly no LAN.  New competitors sold just software and thus had lower overhead and thus a business model that was more friendly to Wall St. analysts. At the same time customers got more sophisticated they didn't need the white-glove, managed, workstations.  

**Source?**

https://en.m.wikipedia.org/wiki/Mentor_Graphics

**Comment by fikrikarim** [comment]
Oh wow! This is my first time hearing Mentor Graphics and electronic design automation. That field is almost entirely new to me. I had to summarize the paragraph a bit, hopefully I still got the main idea correct. Let me know if I miss something.

Thanks for the contribution!

**Comment by tlimoncelli** [comment]
Glad to submit. At the time everyone pointed at another company's recent failure to make the same pivot and claimed MG could do no better.  They had some tough years but succeeded.  (Though, one can question if that success was real or not because years later they got bought out by Siemens.)
