### ISSUE TITLE
Add new company: Berkshire Hathaway

### ISSUE THREAD

**Issue by kykosic** [fikrikarim/companies-with-successful-pivot#16]
**Company Name?**

**What's the company main business today?**
Warren Buffet's multi-national conglomerate holding company

They own companies such as GEICO and Duracell, and they have significant holdings in public companies including Coca-Cola, Kraft, AMEX, Bank of America, and Apple.

**What did the company do in the early days?**
Textile manufacturing

**What caused the company to pivot?**
Basically Buffet was day trading the company. Stanton (running Berkshire Hathaway at the time) then tried to buy him out, but Buffet's offer was undercut at the last minute. Angry by this, Buffet bought a controlling interest in the company and fired him. He then started to pivot from the failing textile business by acquiring a couple of insurance companies (including GEICO). Using capital generated from the insurance business, he continued to reinvest in the many companies they own today.

**Source?**
https://en.wikipedia.org/wiki/Berkshire_Hathaway

**Comment by fikrikarim** [comment]
Added on e3329e8. Thanks a lot for including the summary!
