### ISSUE TITLE
Microsoft

### ISSUE THREAD

**Issue by honnet** [fikrikarim/companies-with-successful-pivot#17]
**Company Name?**
Microsoft

**What's the company main business today?**
Operating systems (mostly?)

**What did the company do in the early days?**
"read the raw data from roadway traffic counters and create reports for traffic engineers"

**What caused the company to pivot?**
They "had only modest success but the experience was instrumental in the creation of Microsoft Corporation a few years later":\
https://web.archive.org/web/20120323162239/http://startup.nmnaturalhistory.org/gallery/story.php?ii=45

**Source?**
https://en.wikipedia.org/wiki/Traf-O-Data

**Comment by fikrikarim** [comment]
I'm wondering whether we could include this, as it seems that Traf-O-Data was a different company?
> As it was, by the time the lone Traf-O-Data began processing traffic tapes in 1975, the two had turned the operation over to Gilbert and moved on to form Microsoft.

**Comment by honnet** [comment]
Not sure, the followings seemed good reasons to me but you decide :)

"Fate: Renamed to Microsoft":\
https://en.wikipedia.org/wiki/Traf-O-Data

"Predecessor: Traf-O-Data":\
https://en.wikipedia.org/wiki/Microsoft

...it depends on what's the purpose of this list...

Anyway, happy new year!

**Comment by fikrikarim** [comment]
Yeah I saw that one. I searched a bit for any source to back that up but got none. This is quite interesting tho so let me know if you have better source. But I guess, maybe just put this on the list. Let people raise another issue if there's any mistake.

Happy new year to you too!

**Comment by fikrikarim** [comment]
Added on 4201a15
