### ISSUE TITLE
Add new company: Soylent

### ISSUE THREAD

**Issue by jacobmarble** [fikrikarim/companies-with-successful-pivot#20]
**Company Name?**
Soylent

**What's the company main business today?**
Meal replacement, nutrition

**What did the company do in the early days?**
Inexpensive cell phone towers. They received $170,000 from YCombinator.

**What caused the company to pivot?**
Cell phone towers were too hard to break into, the founders ran out of money, but still had to eat, so they played around with a meal replacement formula, and invented "Soylent".

**Source?**
https://www.newyorker.com/magazine/2014/05/12/the-end-of-food

https://gaincompliance.com/blog/pivots-and-plans/

**Comment by fikrikarim** [comment]
Nice summary! Added. That's a pretty cool story. Thanks a lot!
