### ISSUE TITLE
Add new company: [IBM]

### ISSUE THREAD

**Issue by derekpankaew** [fikrikarim/companies-with-successful-pivot#21]
**Company Name?**

IBM

**What's the company main business today?**

IT services, cloud computing, and enterprise software

**What did the company do in the early days?**

Sell physical, punch card based tabulating machines.

**What caused the company to pivot?**

Computers

**Source?**

https://www.ibm.com/ibm/history/ibm100/us/en/icons/tabulator/

**Comment by fikrikarim** [comment]
Added. I hope this doesn't make the HN crowds angry. But I think it's still a good lesson to learn from.

Thanks a lot!
