### ISSUE TITLE
Add new company: Okta

### ISSUE THREAD

**Issue by gabrielsroka** [fikrikarim/companies-with-successful-pivot#22]
**Company Name?**
Okta

**What's the company main business today?**
Identity Management

**What did the company do in the early days?**
monitoring and reporting on the reliability of cloud services

**What caused the company to pivot?**
customer demand, "it was unscalable"

**Source?**
https://www.entrepreneur.com/article/375105

**Comment by fikrikarim** [comment]
Hey thanks for the summary. I changed the source to be this tweet as it provides first-hand source of the why they pivoted: https://twitter.com/toddmckinnon/status/1266004294911721480

Let me know if you have better source. Thanks!
