### ISSUE TITLE
Add new company: [Audible]

### ISSUE THREAD

**Issue by PatMan8** [fikrikarim/companies-with-successful-pivot#23]
**Company Name?**
Audible

**What's the company main business today?**
American online audiobook and podcast service that allows users to purchase and stream audiobooks and other forms of spoken word content.

**What did the company do in the early days?**
The company's first product was portable media player known as the Audible Player; released in 1998, the device contained around 4 megabytes of on-board flash storage, which could hold up to two hours of audio.

**What caused the company to pivot?**
Hardware is hard - they had trouble competing with other companies who simply did hardware better (e.g. Apple). So they instead licensed audio codec technology and focused on developing content.

**Source?**
https://www.npr.org/2021/10/29/1050511655/audible-don-katz
https://www.nytimes.com/1998/09/23/business/his-dream-is-that-we-ll-all-hear-little-voices.html
many more at the infamous... https://en.wikipedia.org/wiki/Audible_(service)

**Comment by fikrikarim** [comment]
Whoa that's pretty cool. Thanks for the summary, added!
