### ISSUE TITLE
Add new company: [company name]

### ISSUE THREAD

**Issue by gpapilion** [fikrikarim/companies-with-successful-pivot#24]
**Company Name?**
Pixar

**What's the company main business today?**
Computer Animated Movies

**What did the company do in the early days?**
Sold hardware for computer animation.

**What caused the company to pivot?**
Insufficient sales of hardware product.

**Source?**
https://en.wikipedia.org/wiki/Pixar

**Comment by fikrikarim** [comment]
Thanks for the summary, added!

I wish I could add another sentence of the pivot reason that explain more how they got into animation.
