### ISSUE TITLE
Mazda

### ISSUE THREAD

**Issue by 99px** [fikrikarim/companies-with-successful-pivot#30]
**Mazda**

**Automobile manufacturer**

**Cork-maker as Toyo Cork Kogyo Co., Ltd**

**Bankruptcy. They needed a pivot so they restarted as car manufacturer in 1931 introducing a motorised rickshaw**

**[Source?](https://en.wikipedia.org/wiki/Mazda)**

![mazda](https://user-images.githubusercontent.com/97338892/148641276-56cd16d5-3efa-41f4-8ef7-b065d9132800.png)

**Comment by fikrikarim** [comment]
Added Mazda on 7feb731. Thanks a lot for the great summary!
