### ISSUE TITLE
Add new company: American Express

### ISSUE THREAD

**Issue by valcontent** [fikrikarim/companies-with-successful-pivot#32]
**Company Name?**
American Express 

**What's the company main business today?**
Credit cards, banking, financial services.

**What did the company do in the early days?**
It was a package delivery service! Mostly employing "Expressmen" who carried packages on trains from one city to another.

**What caused the company to pivot?**
They were accused of anticompetitive behaviour like price gouging, and the government literally stripped the Express side of the business from them and nationalised it. Luckily for them they had invented the travelers cheque and money order by then, so they pivoted into becoming mainly a financial services business rather than logistics — mostly against their will.

**Source?**
[American Express](https://www.goodreads.com/book/show/468084) by Peter Grossman

**Comment by fikrikarim** [comment]
Added.

Thanks a lot for the great summary!
