### ISSUE TITLE
Add new company: [company name]

### ISSUE THREAD

**Issue by tanzimsy** [fikrikarim/companies-with-successful-pivot#33]
**Company Name?**

ZipLine

**What's the company main business today?**

Zipline is an American medical product delivery company that is headquartered in South San Francisco, California, which designs, manufactures, and operates delivery drones. The company operates distribution centers in Rwanda, Ghana, and the US.

**What did the company do in the early days?**
A mini-robot powered by your phone: https://www.youtube.com/watch?v=FQEEMpzPZlY

**What caused the company to pivot?**
N/A

**Source?**

**Comment by fikrikarim** [comment]
Wow what a great story. Sorry it took months to add it 😅. Thanks a lot for contributing!
