### ISSUE TITLE
Add new company: [Tandy]

### ISSUE THREAD

**Issue by LarsDu** [fikrikarim/companies-with-successful-pivot#34]
**Company Name?**
Radioshack/Tandy

**What's the company main business today?**
Leather goods (but for a while, electronics)

**What did the company do in the early days?**
Leather goods

**What caused the company to pivot?**
Tandy originally made leather goods for the hobby market. As electronics grew as a hobby in the 70s and 80s, Tandy acquired a small, failing electronics store in Boston called Radioshack. The Tandy TRS-80 was one of the first microcomputers and Radioshack was synonymous with hobby electronics until it went defunct. Tandy Leathergoods still exists today.

**Source?**
https://en.wikipedia.org/wiki/Tandy_Corporation

**Comment by fikrikarim** [comment]
Added! Thanks a lot for contributing!
