### ISSUE TITLE
Add new company: [Polaroid]

### ISSUE THREAD

**Issue by LarsDu** [fikrikarim/companies-with-successful-pivot#35]
**Company Name?**
Polaroid

**What's the company main business today?**
Instant cameras

**What did the company do in the early days?**
Polarized lenses and optics for the armed forces.

**What caused the company to pivot?**
Edwin Land effectively invented one of the first commercially viable processes for creating polarized lenses which he sold to the armed forces for making sunglasses for aviators. Spending most of World War 2 prototyping techniques for night vision and improved optics, after the war, Polaroid pivoted into making instant cameras. Failure to pivot into digital cameras resulted in the bankruptcy of the company several years after the founder passed away.

**Source?**

**Comment by fikrikarim** [comment]
Added! Thanks a lot for contributing!
